### ISSUE TITLE
tensorflow port

### ISSUE THREAD

**Issue by ghost** [cheese-roll/light-anime-face-detector#2]
Mxnet is less used nowadays. Is it possible to port the model to tensorflow via onnx ?

**Comment by ghost** [comment]
FYI: 
https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/issues/17#issuecomment-671675076_

**Comment by cheese-roll** [comment]
Sorry for the late reply. This repository is based on the link you have posted, so the model conversion should be possible using that script. However, the detector code may need to be changed to support the new framework. I might look into it if I have free time.
