### ISSUE TITLE
Creating multiple bounding boxes on the same image which is provided in your repo

### ISSUE THREAD

**Issue by hemanthkumar6661** [cheese-roll/light-anime-face-detector#3]
Facing an issue and getting multiple bounding boxes, the same code block I have tried on your demo img also but getting same results. Attaching the sample please help me out with the same
![abcdfd](https://github.com/cheese-roll/light-anime-face-detector/assets/136590942/56a435b5-fc18-4d67-8603-ffe17a86e4a7)

**Comment by cheese-roll** [comment]
Sorry for the late reply. This repository is really old. There seems to be breaking changes in the `mxnet` library between the time I trained and the latest version (1.9.1). Please install `mxnet==1.6.0` instead to run this repository.
